# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: mongoid_taggable_with_context 1.1.4 ruby lib

Gem::Specification.new do |s|
  s.name = "mongoid_taggable_with_context".freeze
  s.version = "1.1.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Aaron Qian".freeze, "Luca G. Soave".freeze, "John Shields".freeze, "Wilker Lucio".freeze, "Ches Martin".freeze]
  s.date = "2018-11-20"
  s.description = "Add multiple tag fields on Mongoid documents with aggregation capability.".freeze
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".travis.yml",
    "Gemfile",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "glebtv_mongoid_taggable_with_context.gemspec",
    "init.rb",
    "lib/mongoid/taggable_with_context.rb",
    "lib/mongoid/taggable_with_context/aggregation_strategy/map_reduce.rb",
    "lib/mongoid/taggable_with_context/aggregation_strategy/real_time.rb",
    "lib/mongoid/taggable_with_context/aggregation_strategy/real_time_group_by.rb",
    "lib/mongoid/taggable_with_context/deprecations.rb",
    "lib/mongoid/taggable_with_context/version.rb",
    "lib/mongoid_taggable_with_context.rb",
    "spec/mongoid_taggable_with_context_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/lgs/mongoid_taggable_with_context".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "2.7.7".freeze
  s.summary = "Mongoid taggable behaviour".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<mongoid>.freeze, [">= 3.0.0"])
      s.add_development_dependency(%q<rake>.freeze, [">= 0"])
      s.add_development_dependency(%q<rspec>.freeze, [">= 0"])
      s.add_development_dependency(%q<yard>.freeze, [">= 0"])
      s.add_development_dependency(%q<bundler>.freeze, [">= 1.0.0"])
      s.add_development_dependency(%q<jeweler>.freeze, [">= 0"])
    else
      s.add_dependency(%q<mongoid>.freeze, [">= 3.0.0"])
      s.add_dependency(%q<rake>.freeze, [">= 0"])
      s.add_dependency(%q<rspec>.freeze, [">= 0"])
      s.add_dependency(%q<yard>.freeze, [">= 0"])
      s.add_dependency(%q<bundler>.freeze, [">= 1.0.0"])
      s.add_dependency(%q<jeweler>.freeze, [">= 0"])
    end
  else
    s.add_dependency(%q<mongoid>.freeze, [">= 3.0.0"])
    s.add_dependency(%q<rake>.freeze, [">= 0"])
    s.add_dependency(%q<rspec>.freeze, [">= 0"])
    s.add_dependency(%q<yard>.freeze, [">= 0"])
    s.add_dependency(%q<bundler>.freeze, [">= 1.0.0"])
    s.add_dependency(%q<jeweler>.freeze, [">= 0"])
  end
end

